import { serve } from "https://deno.land/std@0.177.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Content-Type": "application/json",
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders, status: 200 });
  }

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      return new Response(JSON.stringify({ error: "Missing Authorization header" }), {
        headers: corsHeaders,
        status: 401,
      });
    }

    const token = authHeader.replace("Bearer ", "");
    const supabaseClient = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
      {
        auth: {
          persistSession: false,
        },
      }
    );

    // Get user from token
    const { data: { user }, error: authError } = await supabaseClient.auth.getUser(token);
    if (authError || !user) {
      return new Response(JSON.stringify({ error: "Invalid token or unauthorized" }), {
        headers: corsHeaders,
        status: 401,
      });
    }

    // Parse request body
    const body = await req.json();
    const {
      bench_press_max_kg,
      squat_max_kg,
      deadlift_max_kg,
      overhead_press_max_kg,
      pullup_rows_max_reps,
      training_days_per_week,
      training_duration_months,
    } = body;

    // Call Gemini API
    const geminiKey = Deno.env.get("GEMINI_API_KEY");
    if (!geminiKey) {
      return new Response(JSON.stringify({ error: "Gemini API key is not configured on backend" }), {
        headers: corsHeaders,
        status: 500,
      });
    }

    const systemPrompt = `You are an expert biomechanics specialist, physical therapist, and elite strength coach. 
Your goal is to analyze a lifter's strength performance and training frequency data to identify potential muscle imbalances, structural vulnerabilities, and strength ratios.
Evaluate based on standard lift ratios (e.g. Bench Press should be ~0.75 of Squat, Squat should be ~0.85 of Deadlift, Overhead Press should be ~0.6 of Bench Press) and training day volume distributions (Push days vs Pull days, Anterior vs Posterior chain).
You must return your output ONLY as a JSON object matching this schema:
{
  "overall_balance_score": 62, // score from 0 to 100 based on overall structural balance
  "imbalances": [
    {
      "area": "Muscle group or movement chain (e.g., Posterior Chain)",
      "severity": "Severity of imbalance: mild / moderate / severe",
      "finding": "What the data indicates (e.g., Squat/Deadlift ratio shows lagging hamstrings)",
      "recommendation": "Corrective exercises and training modifications to fix the issue"
    }
  ],
  "strengths": ["List of movements or muscle groups that show excellent structural ratio or balance"],
  "priority_fixes": ["Body parts or movement patterns requiring immediate attention (e.g., Hamstrings, Upper back volume)"]
}`;

    const userPrompt = `Analyze the following training profile for muscle imbalances:
- Lifts (1RM or estimated maxes in kg):
  * Bench Press: ${bench_press_max_kg || "Not provided"} kg
  * Squat: ${squat_max_kg || "Not provided"} kg
  * Deadlift: ${deadlift_max_kg || "Not provided"} kg
  * Overhead Press: ${overhead_press_max_kg || "Not provided"} kg
  * Pull-ups / Rows Max Reps: ${pullup_rows_max_reps || "Not provided"} reps
- Training Days per Week per Muscle Group:
  ${training_days_per_week ? JSON.stringify(training_days_per_week) : "Not provided"}
- Training Duration (experience): ${training_duration_months || "Unknown"} months
`;

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent?key=${geminiKey}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          contents: [
            {
              role: "user",
              parts: [{ text: `${systemPrompt}\n\n${userPrompt}` }],
            },
          ],
          generationConfig: {
            responseMimeType: "application/json",
          },
        }),
      }
    );

    if (!response.ok) {
      const errText = await response.text();
      throw new Error(`Gemini API call failed: ${errText}`);
    }

    const resJson = await response.json();
    const generatedText = resJson.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!generatedText) {
      throw new Error("No content generated by Gemini");
    }

    const reportData = JSON.parse(generatedText.trim());

    // Save report to database
    const { data: newReport, error: insertError } = await supabaseClient
      .from("muscle_imbalance_reports")
      .insert({
        user_id: user.id,
        bench_press_max: bench_press_max_kg,
        squat_max: squat_max_kg,
        deadlift_max: deadlift_max_kg,
        overhead_press_max: overhead_press_max_kg,
        pullup_rows_max: pullup_rows_max_reps,
        training_days: training_days_per_week,
        training_duration: training_duration_months ? `${training_duration_months} months` : null,
        report_data: reportData,
      })
      .select()
      .single();

    if (insertError) {
      throw new Error(`Failed to save imbalance report to database: ${insertError.message}`);
    }

    return new Response(JSON.stringify({ report: newReport }), {
      headers: corsHeaders,
      status: 200,
    });

  } catch (error) {
    return new Response(JSON.stringify({ error: error.message }), {
      headers: corsHeaders,
      status: 500,
    });
  }
});
